=head1 NAME

Net::OAuth2::Profile::Password - OAuth2 for web-server use

=head1 INHERITANCE

 Net::OAuth2::Profile::Password
   is a Net::OAuth2::Profile

=head1 SYNOPSIS

  my $auth = Net::OAuth2::Profile::Password->new(...);
  $auth->get_access_token(...);

=head1 METHODS

=head2 Constructors

=over 4

=item Net::OAuth2::Profile::Password-E<gt>B<new>(OPTIONS)

 -Option       --Defined in          --Default
  client_id      Net::OAuth2::Profile  <required>
  client_secret  Net::OAuth2::Profile  <required>
  grant_type     Net::OAuth2::Profile  'password'
  scope          Net::OAuth2::Profile  undef
  site           Net::OAuth2::Profile  undef
  token_scheme   Net::OAuth2::Profile  'auth-header:OAuth'
  user_agent     Net::OAuth2::Profile  <created internally>

=over 2

=item client_id => STRING

=item client_secret => STRING

=item grant_type => STRING

=item scope => STRING

=item site => URI

=item token_scheme => SCHEME

=item user_agent => LWP::UserAgent object

=back

=back

=head2 Accessors

=over 4

=item $obj-E<gt>B<bearer_token_scheme>()

See L<Net::OAuth2::Profile/"Accessors">

=item $obj-E<gt>B<grant_type>()

See L<Net::OAuth2::Profile/"Accessors">

=item $obj-E<gt>B<id>()

See L<Net::OAuth2::Profile/"Accessors">

=item $obj-E<gt>B<scope>()

See L<Net::OAuth2::Profile/"Accessors">

=item $obj-E<gt>B<secret>()

See L<Net::OAuth2::Profile/"Accessors">

=item $obj-E<gt>B<site>()

See L<Net::OAuth2::Profile/"Accessors">

=item $obj-E<gt>B<user_agent>()

See L<Net::OAuth2::Profile/"Accessors">

=back

=head2 Actions

=head3 HTTP

=over 4

=item $obj-E<gt>B<request>(REQUEST, [MORE])

See L<Net::OAuth2::Profile/"HTTP">

=item $obj-E<gt>B<request_auth>(TOKEN, (REQUEST | (METHOD, URI, [HEADER, CONTENT])))

See L<Net::OAuth2::Profile/"HTTP">

=back

=head2 Helpers

=over 4

=item $obj-E<gt>B<add_token>(REQUEST, TOKEN, SCHEME)

See L<Net::OAuth2::Profile/"Helpers">

=item $obj-E<gt>B<build_request>(METHOD, URI, PARAMS)

See L<Net::OAuth2::Profile/"Helpers">

=item $obj-E<gt>B<params_from_response>(RESPONSE, REASON)

See L<Net::OAuth2::Profile/"Helpers">

=item $obj-E<gt>B<site_url>((URI|PATH), PARAMS)

See L<Net::OAuth2::Profile/"Helpers">

=back

=head2 Action

=over 4

=item $obj-E<gt>B<get_access_token>(OPTIONS)

 -Option  --Default
  password  <required>
  username  <required>

=over 2

=item password => PASSWORD

=item username => USER

=back

=back

=head1 SEE ALSO

This module is part of Net-OAuth2 distribution version 0.52,
built on January 15, 2013. Website: F<http://perl.overmeer.net>.

=head1 COPYRIGHTS

Copyrights 2013 on the perl code and the related documentation
 by [Mark Overmeer] for SURFnet bv, The Netherlands.  For other contributors see Changes.

Copyrights 2011-12 by Keith Grennan.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
See F<http://www.perl.com/perl/misc/Artistic.html>

